"""Добавление в User полей: crm_id, old_id

Revision ID: 01a36e1bddcc
Revises: 8f437281ae54
Create Date: 2025-05-13 17:05:27.712562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a36e1bddcc'
down_revision: Union[str, None] = '8f437281ae54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('crm_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('old_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_crm_id'), 'users', ['crm_id'], unique=False)
    op.create_index(op.f('ix_users_old_id'), 'users', ['old_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_old_id'), table_name='users')
    op.drop_index(op.f('ix_users_crm_id'), table_name='users')
    op.drop_column('users', 'old_id')
    op.drop_column('users', 'crm_id')
    # ### end Alembic commands ### 