"""Добавление модели Telegram

Revision ID: 3c99dabe0c77
Revises: d20049f54108
Create Date: 2025-05-15 09:28:07.269772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c99dabe0c77'
down_revision: Union[str, None] = 'd20049f54108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_old_id_map')
    op.create_index(op.f('ix_users_old_id'), 'users', ['old_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_old_id'), table_name='users')
    op.create_table('temp_old_id_map',
    sa.Column('new_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('new_id', name='temp_old_id_map_pkey')
    )
    # ### end Alembic commands ### 