"""Добавлены поля в модель Session для пользователей

Revision ID: 8f437281ae54
Revises: 
Create Date: 2025-05-07 14:05:51.896013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f437281ae54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('os', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('platform', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'location')
    op.drop_column('sessions', 'platform')
    op.drop_column('sessions', 'os')
    # ### end Alembic commands ### 